### ISSUE TITLE
any progress?

### ISSUE THREAD

**Issue by alexlii1971** [buddypress/bp-types-ui#1]
Hello, I found your project at:

https://buddypress.trac.wordpress.org/ticket/7179#comment:8

and I leave the message below:

I am really eager to this plugin, but from my view, it is most important to support group member users to filter groups by TYPES at frondend, and it would much great if it can support for sub-types, it would be much great experience for site users, for exameple:
Learning: math, physical, language....
Hobby: Movie, sports....
I know Buddypress does not support Category default, but if some plugin can do the similar thing, it would be much much great, any comments would be appreciated, thanks all.
Alex

**Comment by boonebgorges** [comment]
Hi @alexlii1971 - No work has started in earnest yet on this plugin. I'd expect some activity after BuddyPress 2.7 has been released.

> important to support group member users to filter groups by TYPES at frondend

BP 2.7 will include some infrastructure for building this kind of filter. URLs like example.com/groups/type/math will show groups of the type 'math'. For the moment, it'd be up to your theme to provide the markup for the filter itself.

> it would much great if it can support for sub-types

That's an interesting idea. The group/member type taxonomies are not currently hierarchical, but it's something we could potentially consider. The best place to make this suggestion would be in an enhancement ticket on https://buddypress.trac.wordpress.org.
